apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: "###ZARF_DOMAIN_NAME###"
  dnsNames:
  - "###ZARF_DOMAIN_NAME###"
  issuerRef:
      name: ca-issuer
      kind: Issuer